server:
  port: 0
  
spring:
  application:
    name: stud-kafkaproducerservice
  datasource:
    driver: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/employee?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root
    jpa:
    hibernate:
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
      id:
        new_generator_mappings: false  
  
kafka:
  bootstrapAddress: localhost:9092
      
stud:
  topic:
    name: stud-log
    group-id: group-id
    
emp:
  topic:
    name: emptest
    group-id: group-id

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
  service-url:
    defaultzone: http://localhost:8761/eureka/